version: '3'
services:
  backend:
    build: ./server
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - traccar-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - traccar-network

  db:
    image: postgres:15
    restart: always
    volumes:
      - traccar-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: strongpassword

networks:
  traccar-network:

volumes:
  traccar-db:
